### ISSUE TITLE
How to get the generated file name?

### ISSUE THREAD

**Issue by fenyvesi** [technocreatives/node-red-contrib-polly-tts#2]
Sorry if it's trivial but I can't see. 
I don't know the content of the 2nd ouput of the node, the debug shoes nothing.

Thanks.

**Comment by Rawa** [comment]
The second output of the node is not for debugging it is for errors.

https://github.com/technocreatives/node-red-contrib-polly-tts/blob/master/polly-tts/polly-tts.js#L541

**Comment by fenyvesi** [comment]
Thank you.

Küldte a Windows 10 Posta

Feladó: David Göransson
Elküldve: 2017. június 21., szerda 10:18
Címzett: technocreatives/node-red-contrib-polly-tts
Másolatot kap: George Fenyvesi; Author
Tárgy: Re: [technocreatives/node-red-contrib-polly-tts] How to get thegenerated file name? (#2)

The second output of the node is not for debugging it is for errors.
https://github.com/technocreatives/node-red-contrib-polly-tts/blob/master/polly-tts/polly-tts.js#L541

**Comment by Rawa** [comment]
The path is in "msg.file". Debug the whole message not only the payload.

**Comment by fenyvesi** [comment]
Ok. I am trying it.
Thanks.

Küldte a Windows 10 Posta

Feladó: David Göransson
Elküldve: 2017. június 21., szerda 10:19
Címzett: technocreatives/node-red-contrib-polly-tts
Másolatot kap: George Fenyvesi; Author
Tárgy: Re: [technocreatives/node-red-contrib-polly-tts] How to get thegenerated file name? (#2)

The path is in "msg.file". Debug the whole message not only the payload.

**Comment by fenyvesi** [comment]
I got it. It works like a charm. Thank you.

Küldte a Windows 10 Posta

Feladó: David Göransson
Elküldve: 2017. június 21., szerda 10:19
Címzett: technocreatives/node-red-contrib-polly-tts
Másolatot kap: George Fenyvesi; Author
Tárgy: Re: [technocreatives/node-red-contrib-polly-tts] How to get thegenerated file name? (#2)

The path is in "msg.file". Debug the whole message not only the payload.
