### ISSUE TITLE
Mustache support

### ISSUE THREAD

**Issue by jonferreira** [technocreatives/node-red-contrib-polly-tts#4]
Hi,

I've been working to further improve this node, mostly adding Mustache support and making it look more like the great Ivona node that I used to use - https://www.npmjs.com/package/node-red-contrib-ivona

Unfortunately I seem to have hit a brick wall where I have pretty much all I wanted done but the node is "saving" the mp3 file, in fact it doesn't "say" anything at all.

Any chance you'd be interested on these changes and taking a quick look at my code? - https://github.com/jonferreira/node-red-contrib-polly-tts

Cheers

**Comment by jonferreira** [comment]
Sorted, it was just a typo :)

Let me know if you're interested on this and I'll do a push request

**Comment by Rawa** [comment]
Please do, feel free to make a pull request.
