### ISSUE TITLE
Error installing in Node-Red

### ISSUE THREAD

**Issue by raiderj** [technocreatives/node-red-contrib-polly-tts#5]
Tried to install the node via the Manage Palette in AWS Ubuntu, received this error:

```
0|node-red | 17 Aug 20:29:35 - [info] Installing module: node-red-contrib-polly-tts, version: 0.0.6
0|node-red | 17 Aug 20:29:39 - [info] Installed module: node-red-contrib-polly-tts
0|node-red | 17 Aug 20:29:39 - [info] Added node types:
0|node-red | 17 Aug 20:29:39 - [info]  - node-red-contrib-polly-tts:polly-config : SyntaxError: Unexpected token [
0|node-red | 17 Aug 20:29:39 - [info]  - node-red-contrib-polly-tts:polly : SyntaxError: Unexpected token [

```

**Comment by Rawa** [comment]
Which version of node are you running?

**Comment by raiderj** [comment]
`$ node -v`
`v4.8.4`

**Comment by raiderj** [comment]
This issue might be able to be closed? I tried updating like this:

```
sudo npm install -g
sudo n latest
$ node -v
v4.8.4
```

Then I uninstalled and reinstalled Polly. Now I can see the Polly node, and when I drag & drop to my palette, it shows up. I can also edit the config, which I wasn't able to before. Just did a test, and I'm able to successfully query Polly and get an MP3 in return. Caching also works as well.

Maybe an issue on my end? I don't understand why the update I did made a difference. Seeing your note though made me check and see if I was on the latest. I updated anyway just to make sure.

**Comment by Rawa** [comment]
I think the cause of this is a too old nodejs version. You probably updated to something later than 4.8.4. I'm able to reproduce the same issue with that version.

**Comment by Rawa** [comment]
I found the cause of this issue. I make use of [Destructuring](https://stackoverflow.com/questions/17379277/destructuring-in-node-js) which was not supported in node 4. I've now set a node engine tag in package.json to limit the package to node version 6+.

**Comment by raiderj** [comment]
Thanks for the hard work on the node! This has made integrating quality sounding voice into my project much sleeker. Took me all of 10 minutes to get it functional once I resolved the nodejs issue.

**Comment by Rawa** [comment]
No worries :+1:
